# URL de ligação
spring.datasource.url=jdbc:postgresql://switchback.proxy.rlwy.net:14866/railway
spring.datasource.username=postgres
spring.datasource.password=zLDNnWuUiImoQFwaZTMRkyyftyCPlsrW

# Configurações de Performance (HikariCP)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=540000

# Otimização Hibernate
spring.jpa.properties.hibernate.jdbc.batch_size=25
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.fetch_size=100

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Aumentar o limite de tamanho para permitir imagens Base64
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Porta dinâmica para o Render
server.port=${PORT:8080}